birds/birds/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('predict/', include('predict.urls')),
]

urlpatterns += staticfiles_urlpatterns()

birds/predict/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'predict'

urlpatterns = [
    path('',views.index,name = 'index'),
    path('result/',views.result, name = 'result'),
]

birds/predict/models.py
from django.db import models

# Create your models here.

class Bird(models.Model):
    name = models.CharField(max_length = 50)
    image = models.CharField(max_length = 300)
    number = models.CharField(max_length = 4)
    description = models.CharField(max_length = 1000)

    def __str__(self):
        return self.name

birds/predict/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Bird
from fastai import *
from fastai.vision import *



path = "/home/harsh/SOP/fastai-model/PILANI_BIRDS"

learn = load_learner(path,'birdsofpilani.pkl')
learn.precompute = False
tfms = get_transforms()
# Create your views here.

def index(request):
    return render(request,'predict/index.html')
    # return HttpResponse("<h1>This is the index page</h1>")


def result(request):
    pass
    img = request.FILES['img']
    # learn.load('/home/harsh/SOP/models/birds-stage-1-50-unfrozen')
    im = open_image(img)
    for i in range(len(tfms)):
        im.apply_tfms(tfms[i])
    preds = learn.predict(im)
    context = {
        'preds': preds[0],
    }
    return render(request,'predict/result.html',context)
    #get image from form 
    #predict
    #get array of top 5 probabilities
    #get 5 birds corresponding to top 5
    #send these 5 birds in order through dictionary
    #display in table form in result.html

birds/predict/templates/predict/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Birds Species Classification</title>
    <style>
        body{
        background: url('{% static "predict/images/bg_image.png"%}') no-repeat center center fixed;
        background-size: cover;
        } 
    </style>
</head>

<body >
	
	 <div class="col-lg-12" style="background: rgba(0,0,0,0.6);margin-top:3em;margin-bottom:5em;padding-top:1em;padding-bottom:3em;color:#fff;border-radius:10px;-webkit-box-shadow: 2px 2px 15px 0px rgba(0, 3, 0, 0.7);
-moz-box-shadow:    2px 2px 15px 0px rgba(0, 3, 0, 0.7);
box-shadow:         2px 2px 15px 0px rgba(0, 3, 0, 0.7);">
        <div class="col-sm-12">
            <h1 class="text-center section-title" style="margin-bottom:2em"><b><u>Bird Species Classification</b></u> <br>Developed By<br>Harsh Sulakhe - 2017A7PS0186P <br>Vishal Mittal - 2017A7PS0080P</h1>
        </div>

        <style>
            .img-container {
              text-align: center;
              display: block;
            }
          </style>
        <div class="img-container" >
            <b href=''><img src="{% static 'predict/images/bits_pilani.png' %}"  style="width:350px;height:350px ;" /></b>
        </div>
  
    </div>

    <style>
        .form_class {
          text-align: center;
          display: block;
          color: white;
          font-size: 30px;
        }
    </style>

    <form class="form_class" method="post" enctype="multipart/form-data" action = "{% url 'predict:result'%}">
        {%csrf_token%}
        <label for="img">Select image:</label>
        <input type="file" id="img" name="img" accept="image/*">
        <input type="submit">
    </form>
    

  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

birds/predict/templates/predict/result.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Birds Species Classification</title>
    <style>
        body{
        background: url('{% static "predict/images/bg_image.png"%}') no-repeat center center fixed;
        background-size: cover;
        } 
    </style>
</head>

<body >
    <style>
        .prediction {
            color: white;
            text-align: center;
            margin-top: 100px;
        }
    </style>
    <div class="prediction"  align="middle">
        <h1 class="text-center" style="margin-bottom:20em"><b><u>Prediction</b></u> <br>{{preds}}</h1>
   </div>
    

  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>